### PR TITLE
Add a frontend to camphoric

### PR DESCRIPTION
**Pull request by evinism**
Here's a possible strategy of doing the frontend (shamelessly adapted from [here](https://www.fusionbox.com/blog/detail/create-react-app-and-django/624/)). This is mostly just a starting point for future work. 

The strategy is to add 2 folders in server:
`frontend`: the source directory for all JS + css
`frontend_bootstrap`: a django app which serves the `frontend/build/index.html` file for 2 paths: `/` and `/register/`

Additionally, this adds frontend/build to django's static paths.

Advantages:
1. We don't have to eject CRA yet.
2. We can choose n routes to serve the index bootstrap from really easily, which works well with clientside routing.
3. No conflicts with existing routes because of the opt-in bootstrap pathing. 
4. It's nice and simple, and it should be easy to move to any other technique we'd want.

Problems:
1. Right now, js is served out of `/static/static/js` which is just plain weird.
2. Dev workflow requires you to manually build frontend with `yarn build` if you're not using the yarn dev server
3. I haven't hammered out the yarn dev server workflow yet either.

I'm planning on addressing the problems in followups.

### CODE REVIEW

**Comment by brsaylor** [comment]
Thanks a lot for getting this part going. I have a few preliminary thoughts.

The Django docs advise serving static files directly from a web server in production, for efficiency and security (rather than the django staticfiles app). Serving the bootstrap html via a Django view seems to go against that advice. On the other hand, we are probably aren't going to be running at a scale where that matters a whole lot.

My original idea for the project layout was to have a `server` directory and a `client` directory; all the Django stuff would live in `server` and all the React stuff would live in `client` (or 'frontend'), and they would be minimally coupled. I see how this approach you're suggesting requires the front end files to live inside the Django project. An alternative approach that might also work for now while keeping the client and server code separate:
- Put all the front-end code in its own top-level directory, leave `server` as-is
- Configure the client with the host and port of the Django server (for development, this would be http://127.0.0.1:8000/)
- For development, require running both the yarn dev server and the Django dev server (to me, this doesn't seem too inconvenient)
- For production, configure the web server to serve the bootstrap from /, /register, and /success, static files from /static, the other urls from Django (https://django.readthedocs.io/en/2.2.x/howto/static-files/deployment.html#serving-the-site-and-your-static-files-from-the-same-server). Not sure if we'll easily be able to get that much flexibility from a Django hosting service, but it seems reasonable.

Having said all this, I'm not sure if it's better than what you've got here, and maybe it's more complicated. If we go with this PR, one change I'd want to make is to get rid of the 'server' directory, since it's kind of meaningless here, and move its contents to the top level.

**Comment by evinism** [comment]
Thanks for all these comments!

I tried configuring Django to statically serve the `./frontend/build/` directly at `/`, but django gave me an error saying that it needed some prefix, e.g. `/static/`. If you have any other suggestions of configurations, I'd be super down to try it. Additionally, if you wanna hop on a call, I'd love feedback because I'm kinda making this up as I go along right now.

It's also worth noting that the normal advice for static files may not apply to `index.html` well, since for this single asset, unlike the js and css, we're not agnostic about what path or server to serve from. We have to serve this page from requests to `camphoric.com/` and `camphoric.com/register`, and can't substitute any other path or domain.

**Comment by evinism** [comment]
If we can configure the django hosting service to serve those 3 paths from static, I'm game to do your suggestion. I'm a little sad, but only because we're putting more app config outside of the repo.

Additionally, I'd love to hop on a call to hash this out! It's an important step, and we should get generally right.

**Comment by brsaylor** [comment]
Good point - minimizing the amount of external, server-specific configuration required would be a good thing. Let's chat this weekend if you're available.

**Comment by brsaylor** [comment]
This looks good to me - you should go ahead and merge when you're ready.

**Pull request merged**
